### ISSUE TITLE
[Feature Request]: Implementing Chat App in style share  

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The chat app will help user to generate tailwind components, new ideas etc...
I will use gemini api for the same.

### Use Case

AI integration

### Benefits

User experience will increase.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
what do you mean by chat app? an ai chat bot?

**Comment by MeetDOD** [comment]
no like there will be a new route where user can come and ask ai for components and all

**Comment by VaibhavArora314** [comment]
rather than that maybe we can do one thing which is that on each post we give the user a button "Customize with AI" which redirects to a separate page where the user can send his/her query and the AI will customize and provide accordingly. We can send the first message to the AI with the component after that the user can send messages and interact with the AI.

**Comment by MeetDOD** [comment]
Okay ! I didn't implemented such thing previously but i will try and the idea is interesting ! I will try this aproach :) give me sometime
