### ISSUE TITLE
incorrect text label and heading in new post

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#377]
the first input label should show title and heading of form should change according to languages
update accordingly in all translations
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/159148d0-d224-4d9a-9825-6c1e973c2565)
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/4e680d20-e7c5-42d8-b69a-0baae646a779)

**Comment by Tasneem1028** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by VaibhavArora314** [comment]
@Tasneem1028 any updates?

**Comment by Tasneem1028** [comment]
No updates yet Sir.
And I am planning to quit the program because it is not manageable with my
ongoing internship.
Apologies for the inconveniences.
Let me know if I need to officially convey my discontinuation somewhere.
I hope to contribute in the future.

Apologies again and Thankyou!

Regards

**Comment by MeetDOD** [comment]
@VaibhavArora314 I think this issue is solved with google transaltion ? Now we just have to add like Title because it is blank.

![image](https://github.com/user-attachments/assets/1a88baea-5c69-4ce3-9bb2-4e06f3da769b)

so the heading will the Create new post and the subheading for the first input field will be Title like that !
